name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:
    workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    outputs:
      RELEASE_UPLOAD_URL: ${{steps.upload_url.outputs.RELEASE_UPLOAD_URL}}
    steps:
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'

      # - name: Build IKMDEV Code
      #   uses: ikmdev/maven-clean-install-build-action@v1.1.0
      #   with:
      #     branch_name: ${{env.BRANCH_NAME}}
      #     sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
      #     sonarcloud_host_url: ${{ 'https://sonarcloud.io/'}}
      #     sonarcloud_organization: ${{ github.repository_owner }}
      #     sonarcloud_sources: ${{ 'src/main/java' }}
      #     sonarcloud_projectKey: ${{ github.repository_owner }}_${{ github.event.repository.name }}
      #     sonarcloud_coverage_jacoco_xmlReportPaths: ${{ 'target/site/jacoco/jacoco.xml' }}
      #     sonarcloud_java_binaries: ${{ 'target/classes' }}
      #     sonarcloud_tests: ${{ '' }}
     

  generate_build_installers:
    name: Generate Snapshot Installers
    needs: build-job
    if: contains(github.ref_type, 'tag') == 'false'
    strategy:
      matrix:
        os: [macos-13, macos-14, ubuntu-20.04, windows-2022]
    runs-on: ${{matrix.os}}
    steps:
       - name: Checkout Code Repository
         uses: actions/checkout@v4
    
       - name: Setup Java
         uses: actions/setup-java@v4
         with:
            distribution: 'zulu'
            java-version: '21'

       - name: Composite Action
         uses: ./.github/installer_composite
         with:
            branch_name: ${{ env.BRANCH_NAME }}
            isTag: "false"
            release_upload_url: ${{ '' }}
            github_token: ${{secrets.GITHUB_TOKEN}}
            operating_system: ${{matrix.os}}
        

